# vi: ft=yaml.ansible
---
- name: System Setup Playbook
  become: true
  block:
    - name: Debian
      ansible.builtin.import_tasks: debian.yaml
      when: ansible_facts['os_family'] == 'Debian'

    - name: MacOs
      ansible.builtin.import_tasks: macos.yaml
      when: ansible_facts['os_family'] == 'Darwin'

    - name: Copy Terminfo
      ansible.builtin.copy:
        src: "{{ role_path }}/files/xterm-ghostty.src"
        dest: /tmp/xterm-ghostty.src
        mode: "0777"
