# vi: ft=yaml.ansible
---
- name: Restart ufw
  become: true
  ansible.builtin.systemd_service:
    name: ufw
    state: restarted

- name: Restart fail2ban
  become: true
  ansible.builtin.systemd_service:
    name: ufw
    state: restarted
