# vi: ft=yaml.ansible
---
- name: NFS-SETUP
  become: true
  block:
    - name: Create nfs group
      ansible.builtin.group:
        system: true
        name: nfs-user

    - name: Create nfs user
      ansible.builtin.user:
        system: true
        hidden: true
        createhome: false
        shell: /bin/false
        umask: "007"
        name: nfs-user
        group: nfs-user

    - name: Debian
      ansible.builtin.import_tasks: linux.yaml
      when: >
        (
        ansible_facts['os_family'] == 'Debian'
        or ansible_facts['os_family'] == 'Archlinux'
        )

    - name: MacOs
      ansible.builtin.import_tasks: macos.yaml
      when: ansible_facts['os_family'] == 'Darwin'
