# vi: ft=yaml.ansible
---
- name: Copy tmux.conf
  become: true
  become_user: "{{ user.name }}"
  loop: "{{ users }}"
  loop_control:
    loop_var: user
  ansible.builtin.copy:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "~/.tmux.conf"
    mode: "0664"

- name: Copy zlogin
  ansible.builtin.copy:
    src: "{{ role_path }}/files/zlogin"
    dest: "/etc/zlogin"
    mode: "0664"

- name: Change zprofile
  ansible.builtin.copy:
    src: "{{ role_path }}/files/macoszprofile"
    dest: "/etc/zprofile"
    owner: root
    group: wheel
    mode: "0444"
