# vi: ft=yaml.ansible
---
- name: Configurar usuário na máquina
  hosts: all
  become: true  # Executa como sudo/root

  tasks:
    - name: Create 4G swapfile
      ansible.builtin.shell: |
        swapoff /swapfile || true
        fallocate -l 4G /swapfile
        chmod 600 /swapfile
        mkswap /swapfile
        swapon /swapfile
        grep -q '^/swapfile ' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
      args:
        executable: /bin/bash
      changed_when: true

    - name: Create user nelson
      ansible.builtin.user:
        name: nelson
        password: ""
        shell: /bin/bash
        create_home: true
        groups: sudo
        append: true

    - name: Authorize ssh keys
      ansible.posix.authorized_key:
        key: "{{ lookup('file', '~/.ssh/id_vagrant_ed25519.pub') }}"
        user: "{{ item }}"
      loop:
        - vagrant
        - nelson

    - name: Update Cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Gnome
      ansible.builtin.apt:
        name: gnome-core

    - name: Start GUI
      ansible.builtin.systemd_service:
        name: gdm3
        state: restarted

    - name: Reboot
      ansible.builtin.reboot:
