# vi: set ft=ruby

Vagrant.configure("2") do |config|
  config.vm.define "test-debian" do |debian|
    debian.vm.box = "debian/bookworm64"
    debian.vm.network "private_network", ip: "192.168.57.2"
    debian.vm.hostname = "test-debian"
    
    debian.vm.provider "virtualbox" do |vb|
      vb.name = "test-debian"
      vb.gui = true
      vb.memory = "6144"
      vb.cpus = 2
    end
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "vagrant_playbook.yml"
    ansible.compatibility_mode = "2.0"
  end
end
