# vi: ft=yaml.ansible
---
- name: SSH authentication playbook
  become: true
  block:
    - name: Debian
      ansible.builtin.import_tasks: linux.yaml
      when: >
        (
        ansible_facts['os_family'] == 'Debian'
        or ansible_facts['os_family'] == 'Archlinux'
        )

    - name: MacOs
      ansible.builtin.import_tasks: macos.yaml
      when: ansible_facts['os_family'] == 'Darwin'
